# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cookfollio-ai-services',
                'doc_host': 'https://havspec.github.io',
                'git_url': 'https://github.com/havspec/cookfollio-ai-services',
                'lib_path': 'cookfollio_ai_services'},
  'syms': {'cookfollio_ai_services.core': {'cookfollio_ai_services.core.foo': ('core.html#foo', 'cookfollio_ai_services/core.py')}}}
